### ISSUE TITLE
Various permission and scope issues for Kubernetes deployment

### ISSUE THREAD

**Issue by gfr10598** [m-lab/etl-gardener#20]
Running in Kubernetes in mlab-sandbox, the deduphandler fails when it tries to get the table Metadata.

**Comment by gfr10598** [comment]
Solution:
gke-data-processing-cluster-pool shows that the scope for bigquery is disabled.  8-(

Not sure about which scopes we need, but trying out this:

gcloud container node-pools create pool-1 --cluster=data-processing-cluster --disk-size=10GB --enable-autorepair --enable-autoupgrade --image-type=cos -m n1-highcpu-2  --node-labels=data-processing --num-nodes=2 --zone=us-central1-a --scopes=default,cloud-platform,bigquery,storage-ro,compute-rw,data-store,taskqueue

**Comment by gfr10598** [comment]
I could not reproduce this using unit tests run with same service-account, because apparently scopes are independent of the service account.

**Comment by gfr10598** [comment]
First attempt took more than 30 minutes, and failed with invalid scope.

gcloud container node-pools create pool-5 --cluster=data-processing-cluster --enable-autorepair --enable-autoupgrade --image-type=cos -m n1-standard-2 --num-nodes=2 --zone=us-central1-a --scopes=cloud-platform,bigquery,compute-rw,storage-ro

This succeeds, taking less than 3 minutes.

**Comment by gfr10598** [comment]
Now creating prod cluster:
gcloud container clusters create data-processing-cluster --zone us-central1-a --project=mlab-oti --image-type COS

**Comment by gfr10598** [comment]
For hack, needs access to bucket "gfr".  Added roles to
515150309683-compute@developer.gserviceaccount.com:
legacy storage bucket reader, legacy storage object reader

**Comment by gfr10598** [comment]
FYI, new permission for deploying task queues is "Cloud Tasks Queue Admin"

**Comment by kokosta** [comment]
Log of notes.

**Comment by gfr10598** [comment]
Also need to add datastore:

gcloud container node-pools create gardener-pool --project=mlab-oti --cluster=data-processing-cluster --enable-autorepair --enable-autoupgrade --image-type=cos -m n1-standard-2 --num-nodes=2 --zone=us-central1-a --scopes=bigquery,taskqueue,compute-rw,storage-ro,service-control,service-management,datastore --node-labels=scopes=gardener

To restrict to these instances, use a nodeSelector section with "scopes: gardener"

**Comment by gfr10598** [comment]
Please now refer to README.md for info on garder-pool
