### ISSUE TITLE
traceroute maximum ParseTime too old

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/etl-gardener#204]
Currently, in sandbox, staging, and oti the traceroute dataset reports ~737374 days.

```
SELECT
  TIMESTAMP_DIFF(CURRENT_TIMESTAMP(), min_parse_time, SECOND) / 86400.0 AS value_age_days,
  datatype
FROM (
    SELECT "ndt/traceroute" AS datatype, MIN(ParseInfo.ParseTime) AS min_parse_time
    FROM   `mlab-staging.ndt.traceroute`
)
```

**Comment by yachang** [comment]
SELECT
    ParseInfo.ParseTime AS parse_time,
    Parseinfo.TaskFileName AS task_filename
FROM   `mlab-staging.ndt.traceroute`
WHERE DATE(TestTime)  BETWEEN DATE("2019-06-01") AND DATE("2019-11-30")
GROUP BY parse_time, task_filename
ORDER BY  parse_time ASC


The results show the oldest parse time is 2019/08/29

Row | parse_time | task_filename |  
-- | -- | -- | --
1 | 2019-08-29 04:40:22.416336 UTC | gs://archive-measurement-lab/paris-traceroute/2019/06/05/20190605T000000Z-mlab1-bom01-paris-traceroute-0000.tgz |  
2 | 2019-08-29 04:40:22.416397 UTC | gs://archive-measurement-lab/paris-traceroute/2019/06/05/20190605T000000Z-mlab1-bom01-paris-traceroute-0000.tgz |  
3 | 2019-08-29 04:40:22.416981 UTC | gs://archive-measurement-lab/paris-traceroute/2019/06/05/20190605T000000Z-mlab1-arn04-paris-traceroute-0000.tgz |  
4 | 2019-08-29 04:40:22.417077 UTC | gs://archive-measurement-lab/paris-traceroute/2019/06/05/20190605T000000Z-mlab1-bom01-paris-traceroute-0000.tgz |  
5 | 2019-08-29 04:40:22.417087 UTC | gs://archive-measurement-lab/paris-traceroute/2019/06/05/20190605T000000Z-mlab1-arn04-paris-traceroute-0000.tgz

**Comment by yachang** [comment]
For mlab-staging, the highest value of 

TIMESTAMP_DIFF(CURRENT_TIMESTAMP(), ParseInfo.ParseTime, SECOND) / 86400.0 AS value_age_days

is 77.5 days

For mlab-sandbox, it is 9.38 days

For mlab-oti, it is 90.10 days.

Here is the BQ I used:

=============================

SELECT
    TIMESTAMP_DIFF(CURRENT_TIMESTAMP(), ParseInfo.ParseTime, SECOND) / 86400.0 AS value_age_days,
    Parseinfo.TaskFileName AS task_filename
FROM   `mlab-oti.ndt.traceroute`
WHERE DATE(TestTime)  BETWEEN DATE("2019-06-01") AND DATE("2019-11-30")
GROUP BY value_age_days, task_filename
ORDER BY  value_age_days DESC

**Comment by yachang** [comment]
I check the ParseInfo.ParseTime for traceroute from 2013 to present, the last round time is about 2019/08/22.

So here are the two prod releases: after them, some traceroute tarball failed to be reprocessed.

https://github.com/m-lab/etl-gardener/releases/tag/prod-v1.2.0

https://github.com/m-lab/etl/releases/tag/prod-v1.8.0

**Comment by stephen-soltesz** [comment]
@yachang is it possible the parser has a bug that adds empty rows? There are 178447 rows with what look like 'zero values' for the row, including ParseTime.

I think these empty rows are related to the very large value for `value_age_days`

See the results from this query:

```
SELECT * FROM `mlab-staging.ndt.traceroute` where ParseInfo.ParseTime < TIMESTAMP("2018-01-01")
```

**Comment by yachang** [comment]
Those tarballs failed to be reprocessed are all legacy PT tests:


2019-08-26 12:28:31.757507 UTC | gs://archive-measurement-lab/paris-traceroute/2018/02/01/20180201T000000Z-mlab1-dfw03-paris-traceroute-0000.tgz |  

2019-08-26 12:28:31.781024 UTC | gs://archive-measurement-lab/paris-traceroute/2018/02/01/20180201T000000Z-mlab1-atl05-paris-traceroute-0000.tgz

**Comment by yachang** [comment]
2019-08-22 09:42:15.973029 UTC | gs://archive-measurement-lab/paris-traceroute/2017/01/01/20170101T000000Z-mlab1-ord01-paris-traceroute-0000.tgz


2019-08-21 09:55:29.469167 UTC | gs://archive-measurement-lab/paris-traceroute/2016/01/18/20160118T000000Z-mlab1-ams01-paris-traceroute-0000.tgz


2019-08-20 08:18:16.531861 UTC | gs://archive-measurement-lab/paris-traceroute/2015/03/12/20150312T000000Z-mlab1-acc01-paris-traceroute-0000.tgz


2019-08-19 11:17:28.547837 UTC | gs://archive-measurement-lab/paris-traceroute/2014/01/05/20140105T000000Z-mlab1-atl01-paris-traceroute-0000.tgz


2019-08-19 05:07:20.018290 UTC | gs://archive-measurement-lab/paris-traceroute/2013/05/08/20130508T000000Z-mlab3-akl01-paris-traceroute-0000.tgz

Here is the earliest Parseinfo date for each year.

**Comment by yachang** [comment]
% of tests that failed to be reprocessed:

2019: 6.1*10^6 / 1.9*10^9 = 0.32%
2018: 3.4*10^6 / 1.8*10^9 = 0.17%
2017: 1*10^7/6.5*10^8=1.5%
2016: 6.5*10^7/1.4*10^8=46%

==================================
Here is the BQ I used:

SELECT
ParseInfo.ParseTime AS parse_time,
Parseinfo.TaskFileName AS task_filename
FROM `mlab-oti.ndt.traceroute`
WHERE DATE(TestTime) BETWEEN DATE("2017-01-01") AND DATE("2017-12-31") 
       AND ParseInfo.ParseTime < TIMESTAMP("2019-09-01")
GROUP BY parse_time, task_filename
ORDER BY parse_time ASC

**Comment by yachang** [comment]
For all tarballs with 

ParseInfo.ParseTime < TIMESTAMP("2019-10-01")

The latest Praseinfo time in staging (which more precise to exact PR) is Sept 4th.


Row | parse_time | task_filename |  
-- | -- | -- | --
1 | 2019-09-04 01:38:43.436488 UTC | gs://archive-measurement-lab/paris-traceroute/2017/07/12/20170712T000000Z-mlab3-yyc01-paris-traceroute-0000.tgz

So the effecting PR is 

https://github.com/m-lab/etl/pull/724/

========================

SELECT
ParseInfo.ParseTime AS parse_time,
Parseinfo.TaskFileName AS task_filename
FROM `mlab-staging.ndt.traceroute`
WHERE DATE(TestTime) BETWEEN DATE("2017-01-01") AND DATE("2019-11-30") 
    AND ParseInfo.ParseTime < TIMESTAMP("2019-10-01")
GROUP BY parse_time, task_filename
ORDER BY parse_time DESC

**Comment by gfr10598** [comment]
Looks like this is an ongoing problem.  

SELECT partition_date as pd, AVG(IF(ParseInfo.ParseTime < "2009-01-01",1,0)) AS bad_parse_time_fraction
FROM   `mlab-oti.ndt.traceroute`
GROUP BY partition_date
ORDER BY pd DESC
    

Row | pd | bad_parse_time_fraction |  
-- | -- | -- | --
1 | 2020-01-29 | 0.003312477439537964 |  
2 | 2020-01-28 | 0.002953274295036136 |  
3 | 2020-01-27 | 0.0027694337090092775 |  
4 | 2020-01-26 | 0.003113200959053977

**Comment by yachang** [comment]
Delete empty rows:

DELETE
FROM `mlab-oti.base_tables.traceroute`
WHERE TestTime < "1980-01-01"

**Comment by yachang** [comment]
Updated Summary:

For some paris traceroute tests, 2019/08/19 is the oldest parsing time. 


1 | 2019-08-19 05:34:32.009017 UTC | gs://archive-measurement-lab/paris-traceroute/2013/05/24/20130524T000000Z-mlab3-akl01-paris-traceroute-0000.tgz |  
-- | -- | -- | --
2 | 2019-08-19 05:34:32.009183 UTC | gs://archive-measurement-lab/paris-traceroute/2013/05/24/20130524T000000Z-mlab3-akl01-paris-traceroute-0000.tgz |  
3 | 2019-08-19 05:34:32.009356 UTC | gs://archive-measurement-lab/paris-traceroute/2013/05/24/20130524T000000Z-mlab3-akl01-paris-traceroute-0000.tgz |  
4 | 2019-08-19 05:34:32.009531 UTC | gs://archive-measurement-lab/paris-traceroute/2013/05/24/20130524T000000Z-mlab3-akl01-paris-traceroute-0000.tgz



For scamper tests. 2019/11/03 is the oldest parsing time. 


2019-11-03 18:28:10.209848 UTC | gs://archive-measurement-lab/ndt/traceroute/2019/11/02/20191102T020000.909108Z-traceroute-mlab4-lhr05-ndt.tgz |  
-- | -- | --
2 | 2019-11-03 18:28:10.210001 UTC | gs://archive-measurement-lab/ndt/traceroute/2019/11/02/20191102T020000.909108Z-traceroute-mlab4-lhr05-ndt.tgz |  
3 | 2019-11-03 18:28:10.210251 UTC | gs://archive-measurement-lab/ndt/traceroute/2019/11/02/20191102T020000.909108Z-traceroute-mlab4-lhr05-ndt.tgz |  
4 | 2019-11-03 18:28:10.210374 UTC | gs://archive-measurement-lab/ndt/traceroute/2019/11/02/20191102T020000.909108Z-traceroute-mlab4-lhr05-ndt.tgz

**Comment by stephen-soltesz** [comment]
https://github.com/m-lab/prometheus-support/blob/master/config/federation/bigquery/bq_gardener_parse_time.sql.template#L16

```
SELECT
  TIMESTAMP_DIFF(CURRENT_TIMESTAMP(), min_parse_time, SECOND) / 86400.0 AS value_age_days,
  datatype
FROM (
    SELECT "ndt/web100" AS datatype, MIN(parse_time) AS min_parse_time
    FROM   `mlab-oti.ndt.web100`
  UNION ALL
    SELECT "sidestream/web100" AS datatype, MIN(parse_time) AS min_parse_time
    FROM   `mlab-oti.sidestream.web100`
  UNION ALL
    SELECT "utilization/switch" AS datatype, MIN(parse_time) AS min_parse_time
    FROM   `mlab-oti.utilization.switch`
  UNION ALL
    SELECT "ndt/traceroute" AS datatype, MIN(ParseInfo.ParseTime) AS min_parse_time
    FROM   `mlab-oti.ndt.traceroute`
  UNION ALL
    SELECT "ndt/tcpinfo" AS datatype, MIN(ParseInfo.ParseTime) AS min_parse_time
    FROM   `mlab-oti.ndt.tcpinfo`
  UNION ALL
    SELECT "ndt/ndt5" AS datatype, MIN(ParseInfo.ParseTime) AS min_parse_time
    FROM   `mlab-oti.ndt.ndt5`
)
```

| Row |	value_age_days |	datatype
| -------|---------------------------|--------------
| 1	| 4.6398726851851855 | ndt/ndt5
| 2	| 54.035879629629626 | ndt/tcpinfo
| 3	| 36.23885416666667 | ndt/web100
| 4	| 93.54734953703704 | utilization/switch
| 5	| 737466.8479629629 | ndt/traceroute
| 6	| 13.301666666666666 | sidestream/web100

**Comment by yachang** [comment]
So there are 3 bugs:

1. There is unknown code path that generate empty rows. which will be tracked by https://github.com/m-lab/etl/issues/817

2. For legacy paris traceroute, the oldest parse date is 2019/08/19. Some code change after that date cause the tar ball not be reprocessed. which will be tracked by https://github.com/m-lab/etl/issues/818

3. For scamper tests, the oldest parse date is 2019/11/02. Some code change after that date cause the tar ball not be reprocessed. which will be tracked by https://github.com/m-lab/etl/issues/819

**Comment by mehtab11** [comment]
Fixed; closed.
