### ISSUE TITLE
Gardener reads source archives from archive-* and embargo-* buckets

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/etl-gardener#72]

**Comment by stephen-soltesz** [comment]
Proposal:

* Pass explicit bucket names for archive & embargo buckets with desired `time.Time` instance. to [handler.AddTask](https://github.com/m-lab/etl-gardener/blob/master/cmd/gardener/gardener.go#L172)
* Propagate parameters through to [state.NewTask](https://github.com/m-lab/etl-gardener/blob/master/state/state.go#L130)
* Eliminate [ParsePrefix](https://github.com/m-lab/etl-gardener/blob/master/state/state.go#L157) now that fields are explicit.
* Modify [rex.go:queue()](https://github.com/m-lab/etl-gardener/blob/master/rex/rex.go#L170) to PostDay for both buckets.

**Comment by gfr10598** [comment]
Seems like first decision to make is what to include in the datastore Task entity.  Currently the name includes the full bucket and path.

With separate buckets for embargo and non-embargo, do we want to have separate fields in the Task?  Or just put the root in the task, and have the bucket names implicitly derived from the root?

**Comment by stephen-soltesz** [comment]
@gfr10598 right -- I imagined the Task would record the bucket names as explicit fields, with the `Date` given explicitly (rather than parsed). How does this sound?

**Comment by stephen-soltesz** [comment]
With the newly planned retirement of the embargo system, this issue is now obsolete.
